sudo: required
services:
  - docker
language: bash
install:
  # prepare qemu
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  # build image
  - docker build -t local/tensorflow_serving_tools_docker:build - < ./Dockerfile
script:
  # push image
  - >
    if [ x"$DOCKER_USER" != x ] && [ x"$DOCKER_PASS" != x ]; then
      TAG=$(grep "FROM " Dockerfile | sed 's/.*://')
      docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
      docker tag local/tensorflow_serving_tools_docker:build "$DOCKER_USER/tensorflow_serving_tools_docker:$TAG"
      docker tag local/tensorflow_serving_tools_docker:build "$DOCKER_USER/tensorflow_serving_tools_docker:latest-$TAG"
      docker push "$DOCKER_USER/tensorflow_serving_tools_docker:$TAG"
      docker push "$DOCKER_USER/tensorflow_serving_tools_docker:latest-$TAG"
    fi
    echo "Done!"
